package test.model;

import java.math.BigDecimal;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.acct_num
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    private Integer acctNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    private BigDecimal account;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.acct_num
     *
     * @return the value of account.acct_num
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public Integer getAcctNum() {
        return acctNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.acct_num
     *
     * @param acctNum the value for account.acct_num
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public void setAcctNum(Integer acctNum) {
        this.acctNum = acctNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account
     *
     * @return the value of account.account
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public BigDecimal getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account
     *
     * @param account the value for account.account
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public void setAccount(BigDecimal account) {
        this.account = account;
    }
}