package test.model;

public class Boys {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boys.boy_id
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    private Integer boyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boys.bo_name
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    private String boName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boys.toy_id
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    private Integer toyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boys.boy_id
     *
     * @return the value of boys.boy_id
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public Integer getBoyId() {
        return boyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boys.boy_id
     *
     * @param boyId the value for boys.boy_id
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public void setBoyId(Integer boyId) {
        this.boyId = boyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boys.bo_name
     *
     * @return the value of boys.bo_name
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public String getBoName() {
        return boName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boys.bo_name
     *
     * @param boName the value for boys.bo_name
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public void setBoName(String boName) {
        this.boName = boName == null ? null : boName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boys.toy_id
     *
     * @return the value of boys.toy_id
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public Integer getToyId() {
        return toyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boys.toy_id
     *
     * @param toyId the value for boys.toy_id
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public void setToyId(Integer toyId) {
        this.toyId = toyId;
    }
}