package test.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userId
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userSex
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    private Integer usersex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.areaCode
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    private String areacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userAlias
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    private String useralias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.pictureId
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    private Long pictureid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userIntegral
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    private Integer userintegral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.realName
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userAge
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    private Long userage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userId
     *
     * @return the value of user.userId
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userId
     *
     * @param userid the value for user.userId
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userSex
     *
     * @return the value of user.userSex
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public Integer getUsersex() {
        return usersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userSex
     *
     * @param usersex the value for user.userSex
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public void setUsersex(Integer usersex) {
        this.usersex = usersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.areaCode
     *
     * @return the value of user.areaCode
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.areaCode
     *
     * @param areacode the value for user.areaCode
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userAlias
     *
     * @return the value of user.userAlias
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public String getUseralias() {
        return useralias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userAlias
     *
     * @param useralias the value for user.userAlias
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public void setUseralias(String useralias) {
        this.useralias = useralias == null ? null : useralias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.pictureId
     *
     * @return the value of user.pictureId
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public Long getPictureid() {
        return pictureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.pictureId
     *
     * @param pictureid the value for user.pictureId
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public void setPictureid(Long pictureid) {
        this.pictureid = pictureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userIntegral
     *
     * @return the value of user.userIntegral
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public Integer getUserintegral() {
        return userintegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userIntegral
     *
     * @param userintegral the value for user.userIntegral
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public void setUserintegral(Integer userintegral) {
        this.userintegral = userintegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.realName
     *
     * @return the value of user.realName
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.realName
     *
     * @param realname the value for user.realName
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userAge
     *
     * @return the value of user.userAge
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public Long getUserage() {
        return userage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userAge
     *
     * @param userage the value for user.userAge
     *
     * @mbggenerated Thu Nov 26 19:33:30 CST 2015
     */
    public void setUserage(Long userage) {
        this.userage = userage;
    }
}